### ISSUE TITLE
Add sponsor logos

### ISSUE THREAD

**Issue by mattpiccolella** [adicu/2016.devfe.st#13]

**Comment by eunicekokor** [comment]
who is in charge of sponsor things? They should upload pngs to `img/sponsors`

**Comment by mattpiccolella** [comment]
Working on it

**Comment by samanthaks** [comment]
Hey Matt
I organized them by tier. Is this what you had in mind?

<img width="1247" alt="screenshot 2016-01-21 20 51 08" src="https://cloud.githubusercontent.com/assets/11515314/12500405/d5dd99b2-c080-11e5-8a75-3b68da7e02c4.png">

**Comment by mattpiccolella** [comment]
That's awesome! Great job Sam!

A couple things: could we add a label for each tier? "Gold Level", etc. 

Also, how does it look for the bottom two to be centered? col-3 or whatever, so they have 1.5 times the width.

Really like it!

**Comment by samanthaks** [comment]
I think it's ready now (should just show as list for smaller
<img width="1180" alt="screenshot 2016-01-21 22 24 51" src="https://cloud.githubusercontent.com/assets/11515314/12501671/f9ccd894-c08d-11e5-8ca9-429ea9fa1bd7.png">
 mobile screens)

**Comment by mattpiccolella** [comment]
Looks great! Feel free to push whenever

**Comment by samanthaks** [comment]
I'm 99% sure I made a pull request. Also I don't think I have deploy access.

**Comment by mattpiccolella** [comment]
I can merge and push for you

**Comment by raymondxu** [comment]
reminder that the live site as of now 404s on the microsoft logo @mjp2220

**Comment by mattpiccolella** [comment]
I believe Eunice can address, or others if they know how to fix

**Comment by eunicekokor** [comment]
this looks awesome and I fixed the 404 thing!!
xoxo
