### ISSUE TITLE
Schedule needs locations

### ISSUE THREAD

**Issue by mattpiccolella** [adicu/2016.devfe.st#14]
Prob just adding another field - data is in `data.yml` - should be quick fix

**Comment by eunicekokor** [comment]
how's this?

[image: Inline image 1]
for mon-thurs I just said mudd classrooms since they're different each day

**Comment by mattpiccolella** [comment]
^ I think your image got messed up - I can't see it

**Comment by eunicekokor** [comment]
![image](https://cloud.githubusercontent.com/assets/5273390/12491245/10964aa6-c048-11e5-82ab-86a281dbdbbf.png)
