### ISSUE TITLE
page scroll animation could be faster

### ISSUE THREAD

**Issue by raymondxu** [adicu/2016.devfe.st#16]
It is currently a little too slow in my opinion

**Comment by eunicekokor** [comment]
is 1 second too fast?

**Comment by eunicekokor** [comment]
it's currently 2 seconds

**Comment by raymondxu** [comment]
I tried it locally and I think 1 second is good :+1:

**Comment by raymondxu** [comment]
Changed. b9c83944668c568e1f379b5d86e1d7ebc041507e
