### ISSUE TITLE
Move "If you have other questions, please email us." after the FAQs

### ISSUE THREAD

**Issue by raymondxu** [adicu/2016.devfe.st#17]
This seems more logical because people would have to read all of the FAQ before noticing that it didn't answer their question--then they would be at the bottom of the section.

**Comment by samanthaks** [comment]
can we also change the color? It blends in a bit too much with the dark background.

**Comment by samanthaks** [comment]
<img width="1104" alt="screenshot 2016-01-21 21 06 28" src="https://cloud.githubusercontent.com/assets/11515314/12500624/e200c924-c082-11e5-9978-b4f2f5f33e5f.png">
<img width="1077" alt="screenshot 2016-01-21 21 06 32" src="https://cloud.githubusercontent.com/assets/11515314/12500625/e302fd10-c082-11e5-9a1f-3fc7b712d8b2.png">

when I add the sponsor page I can do this too

**Comment by raymondxu** [comment]
:+1:
