### ISSUE TITLE
Track Info

### ISSUE THREAD

**Issue by yihjenku** [adicu/2016.devfe.st#21]
It would be great if there was a little bit of info for each track so that when people visit the site they know what's up!

**Comment by eunicekokor** [comment]
true! anyone can add to the `data.yml` there are fields for each track!

**Comment by eunicekokor** [comment]
@RaymondXu

**Comment by raymondxu** [comment]
We are waiting on more finalized info on each track before doing them all. I can own this.

**Comment by raymondxu** [comment]
done
