### ISSUE TITLE
Add "flags"/"easter eggs" to dev fee dot estee

### ISSUE THREAD

**Issue by vhshen** [adicu/2016.devfe.st#22]
We are holding an online capture the flag, so it'd be cool if there were flags hidden around the website (ex: click on NYC on the globe and get a flag, inspect element ADI and get a flag in html comments, etc.). If questioms, talk to Bella, Cesar or I! We'll try to come up with a list of flags soon.

**Comment by eunicekokor** [comment]
Sure this flags idea would be awesome!! Looking forward to the list.

It would be cool for someone to volunteer to write the hidden flags into
the html, let me know who so I can give them write access to this
repository!

**Comment by schlosser** [comment]
I think this is moot at this point
