### ISSUE TITLE
Hint that scrolling is possible

### ISSUE THREAD

**Issue by schlosser** [adicu/2016.devfe.st#3]
It would be very easy to not realize that you can scroll the page, maybe throw a "learn more" link down at the bottom?

**Comment by eunicekokor** [comment]
how does this look
![image](https://cloud.githubusercontent.com/assets/5273390/12458600/9ea63962-bf78-11e5-9583-353444eb2f98.png)

**Comment by schlosser** [comment]
I might left align it, because everything else is left aligned, and then put the arrow where it looks good to you (either as it is, centered under "learn more" or immediately to the right of "learn more")

**Comment by eunicekokor** [comment]
It kinda looks really weird left justified. I like this were it is for now and if something else looks better I'll fix it!

**Comment by schlosser** [comment]
cool :)
