### ISSUE TITLE
add tracks page

### ISSUE THREAD

**Issue by eunicekokor** [adicu/2016.devfe.st#4]
![screenshot 2016-01-20 12 41 52](https://cloud.githubusercontent.com/assets/5273390/12457655/bfefdfc4-bf73-11e5-83c0-951fd59095c7.png)

thoughts on background color, wording etc.
should we just deploy names or have a description, too?

**Comment by schlosser** [comment]
I would offer that we don't need to be as inspirational in the subtitle, and be a little bit more clear about what tracks are and how you should use them.

Something like "Learn at your own pace, picking from the tracks that excite you.  Work on one track at a time, or bounce between them!" maybe?

Also, I think we could make the design more exciting somehow.  I think the black on darker gray is kinda moody.  Could we lighten it up, and use a bit more color?  

The only other suggestion would be that "Tracks" is pretty huge.  We might be able to pair it down a bit, and bring the eye to focus on the track titles, cause that's what we really want to get across

**Comment by raymondxu** [comment]
+1 on the colors being more vibrant. Maybe we could use the blue from the devfe.st main page?

I would say for now we can wait on the descriptions because the content for the product and data science tracks isn't finalized yet so we can't accurately describe them. It would be cool to have, later, a brief description under each track name like: "Build a Reading List App with Flask, HTML, and CSS."

**Comment by schlosser** [comment]
Agreed!  Maybe not a background color, but if we could include some blue, that could be cool

**Comment by eunicekokor** [comment]
right now the color order is 
blue
[anything] 
black
do we want it to be blue twice? I had it white, and it looks good. I'll add some blue to it and see what happens

Tracks is the same size as FAQ, all the headers same size, we can make them smaller though

**Comment by schlosser** [comment]
jinx?  White sounds good to me, with some colored accents maybe?

And yeah I think `.page-head` and `.page-info-head` can come down a bit.

**Comment by eunicekokor** [comment]
![screenshot 2016-01-20 14 21 21](https://cloud.githubusercontent.com/assets/5273390/12460318/32c8285a-bf81-11e5-826a-bcd30d18abaa.png)

**Comment by schlosser** [comment]
Looks great!  To give more focus to the tracks, I would tone down (maybe make it a dark gray) the subtitle.

Def makes a big difference with the white bg

**Comment by eunicekokor** [comment]
the "Presented by" subtitle or the "Learn at your own pace" one?

**Comment by schlosser** [comment]
the "Learn at your own pace" one

**Comment by eunicekokor** [comment]
![image](https://cloud.githubusercontent.com/assets/5273390/12464829/01b9b40a-bf99-11e5-9480-d9bd67c757ae.png)

**Comment by schlosser** [comment]
Looks great!
