### ISSUE TITLE
add link to facebook/adi

### ISSUE THREAD

**Issue by eunicekokor** [adicu/2016.devfe.st#5]
![image](https://cloud.githubusercontent.com/assets/5273390/12459508/06ff6ec6-bf7d-11e5-9720-0746353fd6cd.png)

added at the end of the FAQ, however we can put it anywhere

**Comment by schlosser** [comment]
Ohhh we should put FB rsvp at the end of the registration form

**Comment by schlosser** [comment]
We could maybe do this in a bright-colored (red?) footer?  Like as big as the header even?  Could be cool to do a "OK, now register" thing, and then put these buttons below?

**Comment by raymondxu** [comment]
@danrschlosser do you mean we should have another Register button in the footer or just have the Facebook event link?

**Comment by schlosser** [comment]
I'm saying make the footer badass, and have a big, full pitch for the register button, as well as a big, full pitch for the FB event

**Comment by schlosser** [comment]
(badass ~= ~1 screen tall)

**Comment by eunicekokor** [comment]
yeah I'm having a hard time visualizing also!

**Comment by schlosser** [comment]
Examples: 
- the red footer here: http://focuslabllc.com/
- the part right before the footer here: https://generalassemb.ly/

It doesn't have to be in the footer persay, just another section that has the same purpose / organization as the header.

**Comment by mattpiccolella** [comment]
Are we saying this is done? I see a footer with these things that looks very nice!

![image](https://cloud.githubusercontent.com/assets/4534415/12490162/2502c678-c042-11e5-8fed-dffab22ee4ba.png)

**Comment by raymondxu** [comment]
Closing because done.
