### ISSUE TITLE
If you resize the window, the navbar snaps at the wrong place

### ISSUE THREAD

**Issue by schlosser** [adicu/2016.devfe.st#6]
We could either compute the vertical position on scroll every time, or just recompute on resize.

**Comment by eunicekokor** [comment]
where does it snap
and which direction for resize / how do I reproduce?

**Comment by schlosser** [comment]
My understanding is that you compute the scroll height at which you should pin / unpin the navbar once, instead of computing it every scroll, or every resize.

**Comment by schlosser** [comment]
attach a resize handler: https://api.jquery.com/resize/
