### ISSUE TITLE
DevFest logo is a bit cramped

### ISSUE THREAD

**Issue by schlosser** [adicu/2016.devfe.st#8]
It might look better if we gave it the same padding (visually) as the text in the navbar.

**Comment by samanthaks** [comment]
<img width="1150" alt="screenshot 2016-01-20 20 52 30" src="https://cloud.githubusercontent.com/assets/11515314/12469212/c5f7647a-bfb7-11e5-8797-73c16e921e2a.png">

How's this?

**Comment by schlosser** [comment]
Would it be possible to try making it so it's as tall as the text on the right is? right now it's much larger.

**Comment by samanthaks** [comment]
<img width="1149" alt="screenshot 2016-01-20 21 00 03" src="https://cloud.githubusercontent.com/assets/11515314/12469314/ccfa51dc-bfb8-11e5-96e9-06a94910d4b4.png">

Just changed the relative size of the logo and the padding

**Comment by schlosser** [comment]
love it!

**Comment by eunicekokor** [comment]
nice!!! :100:
